// Plan mode for Horus - Hermes-style planning

import { promises as fs } from 'fs';
import { join, isAbsolute } from 'path';

export interface PlanStep {
  id: string;
  description: string;
  tool: string;
  args: Record<string, any>;
  checkpoint: boolean;
  dependsOn?: string[];
}

export interface Plan {
  objective: string;
  context: string;
  steps: PlanStep[];
  estimatedTokens: number;
  rollbackStrategy: string;
}

export class PlanManager {
  private cwd: string;
  private planPath: string;

  constructor(cwd: string) {
    this.cwd = cwd;
    this.planPath = join(cwd, 'PLAN.md');
  }

  async generate(objective: string, context: string): Promise<Plan> {
    // In a real implementation, this would use the LLM to generate a plan
    // For now, return a template
    const plan: Plan = {
      objective,
      context,
      steps: [
        {
          id: '1',
          description: 'Analyze current state',
          tool: 'view',
          args: { path: '.' },
          checkpoint: true,
        },
        {
          id: '2',
          description: 'Search for relevant code',
          tool: 'search',
          args: { query: 'TODO' },
          checkpoint: false,
        },
        {
          id: '3',
          description: 'Implement changes',
          tool: 'edit',
          args: { path: 'src/example.ts', oldString: '', newString: '' },
          checkpoint: true,
        },
      ],
      estimatedTokens: 15000,
      rollbackStrategy: 'Each checkpoint creates a git commit. Rollback with checkpoint tool.',
    };

    return plan;
  }

  async writePlan(plan: Plan): Promise<void> {
    const content = this.formatPlan(plan);
    await fs.writeFile(this.planPath, content, 'utf-8');
  }

  async readPlan(): Promise<Plan | null> {
    try {
      const content = await fs.readFile(this.planPath, 'utf-8');
      return this.parsePlan(content);
    } catch {
      return null;
    }
  }

  async exists(): Promise<boolean> {
    try {
      await fs.access(this.planPath);
      return true;
    } catch {
      return false;
    }
  }

  async delete(): Promise<void> {
    try {
      await fs.unlink(this.planPath);
    } catch {
      // Ignore if doesn't exist
    }
  }

  private formatPlan(plan: Plan): string {
    const lines: string[] = [];
    
    lines.push(`# Plan: ${plan.objective}`);
    lines.push('');
    lines.push('## Objective');
    lines.push(plan.objective);
    lines.push('');
    lines.push('## Context');
    lines.push(plan.context);
    lines.push('');
    lines.push('## Steps');
    
    for (const step of plan.steps) {
      lines.push('');
      lines.push(`### Step ${step.id}: ${step.description}`);
      lines.push(`- **Tool**: ${step.tool}`);
      lines.push(`- **Checkpoint**: ${step.checkpoint ? 'Yes' : 'No'}`);
      if (step.dependsOn) {
        lines.push(`- **Depends on**: ${step.dependsOn.join(', ')}`);
      }
      lines.push(`- **Arguments**:`);
      lines.push('```json');
      lines.push(JSON.stringify(step.args, null, 2));
      lines.push('```');
    }
    
    lines.push('');
    lines.push('## Rollback Strategy');
    lines.push(plan.rollbackStrategy);
    lines.push('');
    lines.push('## Estimated Tokens');
    lines.push(`${plan.estimatedTokens}`);
    lines.push('');
    lines.push('---');
    lines.push('Status: PENDING');
    lines.push('Generated by Horus');
    
    return lines.join('\n');
  }

  private parsePlan(content: string): Plan {
    // Simple parsing - in production, use a proper markdown parser
    const lines = content.split('\n');
    
    const plan: Plan = {
      objective: 'Unknown',
      context: '',
      steps: [],
      estimatedTokens: 0,
      rollbackStrategy: '',
    };

    let inSteps = false;
    let currentStep: Partial<PlanStep> = {};

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];

      if (line.startsWith('# Plan:')) {
        plan.objective = line.replace('# Plan:', '').trim();
      } else if (line === '## Objective') {
        plan.objective = lines[i + 1]?.trim() || plan.objective;
      } else if (line === '## Context') {
        let contextLines: string[] = [];
        let j = i + 1;
        while (j < lines.length && !lines[j].startsWith('##')) {
          contextLines.push(lines[j]);
          j++;
        }
        plan.context = contextLines.join('\n').trim();
      } else if (line === '## Steps') {
        inSteps = true;
      } else if (line.startsWith('### Step')) {
        if (currentStep.id) {
          plan.steps.push(currentStep as PlanStep);
        }
        const match = line.match(/Step (\d+):\s*(.+)/);
        currentStep = {
          id: match?.[1] || String(plan.steps.length + 1),
          description: match?.[2] || line,
        };
      } else if (line.startsWith('- **Tool**')) {
        currentStep.tool = line.match(/:\s*(.+)/)?.[1]?.trim();
      } else if (line.startsWith('- **Checkpoint**')) {
        currentStep.checkpoint = line.includes('Yes');
      } else if (line.startsWith('```json')) {
        // Parse args
        let jsonLines: string[] = [];
        let j = i + 1;
        while (j < lines.length && lines[j] !== '```') {
          jsonLines.push(lines[j]);
          j++;
        }
        try {
          currentStep.args = JSON.parse(jsonLines.join('\n'));
        } catch {
          currentStep.args = {};
        }
        i = j;
      } else if (line === '## Rollback Strategy') {
        inSteps = false;
        let strategyLines: string[] = [];
        let j = i + 1;
        while (j < lines.length && !lines[j].startsWith('##')) {
          strategyLines.push(lines[j]);
          j++;
        }
        plan.rollbackStrategy = strategyLines.join('\n').trim();
      } else if (line === '## Estimated Tokens') {
        plan.estimatedTokens = parseInt(lines[i + 1]?.trim() || '0', 10);
      }
    }

    // Add last step
    if (currentStep.id) {
      plan.steps.push(currentStep as PlanStep);
    }

    return plan;
  }
}

// Tool definitions for plan-related tools
export const planTools = {
  checkpoint: {
    name: 'checkpoint',
    description: 'Create a checkpoint for rollback',
    parameters: {
      type: 'object',
      properties: {
        name: { type: 'string', description: 'Checkpoint name' },
      },
      required: ['name'],
    },
  },
  rollback: {
    name: 'rollback',
    description: 'Rollback to a checkpoint',
    parameters: {
      type: 'object',
      properties: {
        checkpointId: { type: 'string', description: 'Checkpoint ID (omit for latest)' },
      },
    },
  },
  plan: {
    name: 'plan',
    description: 'Generate a plan for the task',
    parameters: {
      type: 'object',
      properties: {
        objective: { type: 'string', description: 'What to accomplish' },
        context: { type: 'string', description: 'Additional context' },
      },
      required: ['objective'],
    },
  },
};
